### PR TITLE
添加uos请求头支持

### PR DESCRIPTION
**Pull request by gengchen528**

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Could you please make the CI passed before we can continue viewing this PR?

Thank you very much!

**Comment by gengchen528** [comment]
> Could you please make the CI passed before we can continue viewing this PR?
> 
> Thank you very much!

ok

**Review by huan — APPROVED** [review]
LGTM

**Comment by jeasoncc** [comment]
thank you

**Comment by zrmzack** [comment]
nice

**Comment by zywaiting** [comment]
是不是不行了，这几天没登，登不上去了，直接登陆失败
<error><ret>1203</ret><message>登录失败。</message></error>

**Comment by zywaiting** [comment]
<error><ret>1203</ret><message>登录失败。</message></error>

**Comment by zywaiting** [comment]
`<error><ret>1203</ret><message>登录失败。</message></error>`

**Comment by HangJau** [comment]
这就不行了？ 正准备用呢

**Comment by akiomaki7007** [comment]
https://github.com/wechaty/puppet-wechat/pull/129#issuecomment-1004867719

**Pull request merged**
