### PR TITLE
Allow users to use their self-generated extspam

### PR DESCRIPTION
**Pull request by fi6**
Nothing will change if they don't customize their token, but will allow those who wants to use the token to setup without changing the raw code

### CODE REVIEW

**Comment by fi6** [comment]
@huan Is there anything that I need to change with this PR or is there anything left to do before I submit it? Looks like it's been some days but this is still under review.

**Review by huan — CHANGES_REQUESTED** [review]
LGTM

Sorry for the delay and thank you for adding this great feature to the UOS puppet!

It's so smart to reuse the token for this puppet.

Just one more thing: could you please also add docs to our README so that other users can learn how to specify the `extspam` when they are using this puppet?

It will be better if see can support the `WECHATY_PUPPET_WECHAT_TOKEN` environment variable so that it can be easy to be deployed.

**Comment by fi6** [comment]
added environment support and brief readme instructions

**Review by huan — APPROVED** [review]

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited fi6 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
